---
AWSTemplateFormatVersion: '2010-09-09'

Description: Creates an S3 Bucket, IAM Policies, and SageMaker Notebook needed for the Amazon Personalize Immersion Day.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "SageMaker notebook instance"
        Parameters:
          - NotebookName
          - VolumeSize
      - Label:
          default: "Industry"
        Parameters:
          - domain
    ParameterLabels:
      NotebookName:
        default: "Instance name"
      VolumeSize:
        default: "Volume size"
      domain:
        default: "Industry domain"

Parameters:
  NotebookName:
    Type: String
    Default: AmazonPersonalizeImmersionDay
    Description: Enter the name of the SageMaker notebook instance. Default is AmazonPersonalizeImmersionDay.

  VolumeSize:
    Type: Number
    Default: 64
    MinValue: 5
    MaxValue: 16384
    ConstraintDescription: Must be an integer between 5 (GB) and 16384 (16 TB).
    Description: Enter the size of the SageMaker notebook instance EBS volume in GB.

  domain:
    Type: String
    Default: Media
    Description: Select the industry domain (Retail, Media, or CPG) to use for the Amazon Personalize Immersion Day.
    AllowedValues:
      - 'Retail'
      - 'Media'
      - 'CPG'

Resources:
  SAMArtifactsBucket:
    Type: AWS::S3::Bucket

  # SageMaker Execution Role
  SageMakerIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/IAMFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"
        - "arn:aws:iam::aws:policy/AWSLambda_FullAccess"
        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
        - "arn:aws:iam::aws:policy/service-role/AmazonPersonalizeFullAccess"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
      Policies:
        - PolicyName: EventBridgeAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "events:*"
                Resource: "*"

  # SageMaker notebook
  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t3.medium"
      NotebookInstanceName: !Ref NotebookName
      RoleArn: !GetAtt SageMakerIamRole.Arn
      VolumeSizeInGB: !Ref VolumeSize
      LifecycleConfigName: !GetAtt AmazonPersonalizeMLOpsLifecycleConfig.NotebookInstanceLifecycleConfigName
      PlatformIdentifier: notebook-al2-v1

  AmazonPersonalizeMLOpsLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnCreate:
        - Content:
            Fn::Base64:
              !Sub |
                #!/bin/bash
                sudo -u ec2-user -i <<'EOF'
                source /home/ec2-user/anaconda3/bin/activate JupyterSystemEnv
                jupyter labextension install @jupyter-widgets/jupyterlab-manager
                source /home/ec2-user/anaconda3/bin/deactivate
                git clone https://github.com/aws-solutions/maintaining-personalized-experiences-with-machine-learning.git
                cd maintaining-personalized-experiences-with-machine-learning/source
                source /home/ec2-user/anaconda3/bin/activate "mxnet_latest_p37"
                pip install cdk_solution_helper_py/helpers_common
                pip install scheduler/common
                source /home/ec2-user/anaconda3/bin/deactivate
                EOF
      OnStart:
        - Content:
            Fn::Base64:
              !Sub |
                #!/bin/bash
                sudo -u ec2-user -i <<'EOF'
                cd /home/ec2-user/SageMaker/
                git clone https://github.com/aws-samples/amazon-personalize-immersion-day.git
                cd /home/ec2-user/SageMaker/amazon-personalize-immersion-day/automation/ml_ops/
                nohup sh deploy.sh "${SAMArtifactsBucket}" "${domain}" &
                EOF